services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: test
      POSTGRES_DB: taxi-app
    ports:
      - '5432:5432'

  backend:
    build: ./backend
    ports:
      - '8080:8080'
    environment:
      - GOOGLE_API_KEY=${GOOGLE_API_KEY}
      - DATABASE_URL=postgresql://postgres:test@postgres:5432/taxi-app
    command: ./docker-entrypoint.sh
    depends_on:
      - postgres

  frontend:
    build: ./frontend
    ports:
      - "80:80"
    depends_on:
      - backend
