services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: which-way-now
    ports:
      - '5432:5432'

  backend:
    build: ./backend
    ports:
      - '8080:8080'
    environment:
      - GOOGLE_API_KEY=${GOOGLE_API_KEY}
      - DATABASE_URL=postgresql://postgres:admin@postgres:5432/which-way-now
    command: ./docker-entrypoint.sh
    depends_on:
      - postgres

  frontend:
    build: ./frontend
    ports:
      - "80:80"
    environment:
      - VITE_BACKEND_DOMAIN=backend
    depends_on:
      - backend
